### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/mrrhp-apache#111]
In GitLab by @yuu-eguci on Oct 12, 2019, 18:28

## What to do actually

500 error happens when access to a post that has the conditions below.

- Exists.
- Doesn't have publish_at parameter.

It should show 404 error page.

```
Server Error happened!
Request uri: https://www.mrrhp.com/ja/ravpower-20100-review
HTTP_HOST: www.mrrhp.com
HTTP_REFERER: https://www.mrrhp.com/admin/app/post/
HTTP_USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
QUERY_STRING: 
REMOTE_ADDR: 114.154.239.201
REQUEST_METHOD: GET
Traceback (most recent call last):
 File "/env3.6/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
   response = get_response(request)
 File "/env3.6/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
   response = self.process_exception_by_middleware(e, request)
 File "/env3.6/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/vagrant/app/views_lang.py", line 18, in post_ja
   return views.post(request, consts.Lang.JA, code)
 File "/vagrant/app/views.py", line 54, in post
   if post_bizlogic.is_available_post_obj(post_obj):
 File "/vagrant/app/bizlogic/post_bizlogic.py", line 22, in is_available_post_obj
   return post_obj.publish_at <= timezone.now()
TypeError: '<=' not supported between instances of 'NoneType' and 'datetime.datetime'
```

**Comment by yuu-eguci** [comment]
In GitLab by @yuu-eguci on Oct 30, 2019, 20:52

mentioned in merge request !99

**Comment by yuu-eguci** [comment]
In GitLab by @yuu-eguci on Oct 30, 2019, 20:52

created merge request !99 to address this issue

**Comment by yuu-eguci** [comment]
In GitLab by @yuu-eguci on Oct 30, 2019, 20:55

mentioned in commit ddf713f611f81cb3bc17953127c63cfc41d23eb5

**Comment by yuu-eguci** [comment]
In GitLab by @yuu-eguci on Oct 30, 2019, 20:55

closed via merge request !99

**Comment by yuu-eguci** [comment]
In GitLab by @yuu-eguci on Oct 30, 2019, 20:55

mentioned in commit fa9d6a9f0ea0224d3b58eebdd4d599cd77f939ed
