### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by yuu-eguci** [yuu-eguci/mrrhp-apache#112]
In GitLab by @yuu-eguci on Nov 1, 2019, 09:16

## What to do actually

- Fix 500 error below.

```
Server Error happened!
Request uri: https://www.mrrhp.com/ja/%EF%BC%9Ca%20href%3D
HTTP_HOST: www.mrrhp.com
HTTP_REFERER: None
HTTP_USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
QUERY_STRING: 
REMOTE_ADDR: 153.194.161.209
REQUEST_METHOD: GET
Traceback (most recent call last):
 File "/env3.6/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
   response = get_response(request)
 File "/env3.6/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
   response = self.process_exception_by_middleware(e, request)
 File "/env3.6/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/vagrant/app/views_lang.py", line 18, in post_ja
   return views.post(request, consts.Lang.JA, code)
 File "/vagrant/app/views.py", line 49, in post
   post_obj = post_bizlogic.get_post_obj_by_code(code)
 File "/vagrant/app/bizlogic/post_bizlogic.py", line 20, in get_post_obj_by_code
   if not post.publish_at:
AttributeError: 'NoneType' object has no attribute 'publish_at'
```

**Comment by yuu-eguci** [comment]
In GitLab by @yuu-eguci on Nov 1, 2019, 10:09

created merge request !100 to address this issue

**Comment by yuu-eguci** [comment]
In GitLab by @yuu-eguci on Nov 1, 2019, 10:09

mentioned in merge request !100

**Comment by yuu-eguci** [comment]
In GitLab by @yuu-eguci on Nov 1, 2019, 10:12

mentioned in commit 1dd0527d834dc7f2d71d9c76941132dd7b50e8a4

**Comment by yuu-eguci** [comment]
In GitLab by @yuu-eguci on Nov 1, 2019, 10:14

closed via merge request !100

**Comment by yuu-eguci** [comment]
In GitLab by @yuu-eguci on Nov 1, 2019, 10:14

mentioned in commit 9ca7b81176f3f15d35bff1113649d9b03459b434
